// In The News — article feed API layer
// Mock data for hackathon; wire to TinyFish Edge Function when ready

export type ArticleType = 'news' | 'opinion' | 'blog' | 'press_release'

export interface PersonArticle {
  id: string
  person_id: string
  title: string
  source: string
  url: string
  image_url: string | null
  snippet: string
  published_date: string
  content_type: ArticleType
}

// ── Mock article data keyed by person_id ────────────────────────────

const MOCK_ARTICLES: Record<string, PersonArticle[]> = {
  // ── Senator Elizabeth Warren (S001217) ──
  S001217: [
    {
      id: 'art-S001217-1',
      person_id: 'S001217',
      title: 'Warren Introduces Bill to Cap Student Loan Interest at 3%',
      source: 'AP News',
      url: 'https://apnews.com/article/warren-student-loan-cap',
      image_url: 'https://picsum.photos/seed/art-s1-1/400/225',
      snippet: 'The legislation would retroactively lower interest rates on federal student loans, potentially affecting 43 million borrowers nationwide.',
      published_date: '2026-03-18T10:30:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001217-2',
      person_id: 'S001217',
      title: 'Warren Grills Tech CEO Over Data Privacy Practices at Senate Hearing',
      source: 'Reuters',
      url: 'https://reuters.com/article/warren-tech-hearing',
      image_url: 'https://picsum.photos/seed/art-s1-2/400/225',
      snippet: 'Senator Warren pressed executives on algorithmic bias and data collection affecting minors in a heated three-hour committee session.',
      published_date: '2026-03-14T15:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001217-3',
      person_id: 'S001217',
      title: "Opinion: Warren's Wealth Tax Plan Deserves a Second Look",
      source: 'Boston Globe',
      url: 'https://bostonglobe.com/opinion/warren-wealth-tax',
      image_url: null,
      snippet: 'As inequality reaches new heights, the Massachusetts senator\'s proposal to tax ultra-high net worth individuals could fund universal childcare and close the deficit.',
      published_date: '2026-03-10T08:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-S001217-4',
      person_id: 'S001217',
      title: 'Warren Pushes for Universal Childcare in New Budget Proposal',
      source: 'CNN',
      url: 'https://cnn.com/politics/warren-childcare-budget',
      image_url: 'https://picsum.photos/seed/art-s1-4/400/225',
      snippet: 'The proposal includes $70 billion in annual funding for free childcare for families earning under $100,000, funded through corporate tax adjustments.',
      published_date: '2026-03-06T12:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001217-5',
      person_id: 'S001217',
      title: 'How Warren Became Silicon Valley\'s Most Feared Regulator',
      source: 'Wired',
      url: 'https://wired.com/story/warren-tech-regulation',
      image_url: 'https://picsum.photos/seed/art-s1-5/400/225',
      snippet: 'From breakup proposals to AI oversight bills, a deep dive into the senator\'s decade-long crusade to rein in Big Tech.',
      published_date: '2026-02-28T09:00:00Z',
      content_type: 'blog',
    },
    {
      id: 'art-S001217-6',
      person_id: 'S001217',
      title: 'Senator Warren\'s Office Announces Consumer Protection Town Halls Across Massachusetts',
      source: 'Office of Sen. Warren',
      url: 'https://warren.senate.gov/newsroom/press-releases/town-halls',
      image_url: null,
      snippet: 'Five town halls across the state will focus on predatory lending, medical debt, and junk fees affecting working families.',
      published_date: '2026-02-20T11:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-S001217-7',
      person_id: 'S001217',
      title: 'Warren Joins Bipartisan Coalition to Regulate AI in Financial Services',
      source: 'CNBC',
      url: 'https://cnbc.com/warren-ai-finance-regulation',
      image_url: 'https://picsum.photos/seed/art-s1-7/400/225',
      snippet: 'The bill would require algorithmic transparency in credit scoring, lending decisions, and insurance underwriting powered by AI models.',
      published_date: '2026-02-15T14:30:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001217-8',
      person_id: 'S001217',
      title: 'Warren Calls for Investigation Into Rising Grocery Prices',
      source: 'NPR',
      url: 'https://npr.org/warren-grocery-prices',
      image_url: 'https://picsum.photos/seed/art-s1-8/400/225',
      snippet: 'Citing new FTC data, the senator alleges that corporate consolidation in the grocery industry is driving price increases beyond inflation.',
      published_date: '2026-02-08T10:00:00Z',
      content_type: 'news',
    },
  ],

  // ── Senator Ted Cruz (C001098) ──
  C001098: [
    {
      id: 'art-C001098-1',
      person_id: 'C001098',
      title: 'Cruz Introduces Border Security Overhaul With $12B in Funding',
      source: 'Fox News',
      url: 'https://foxnews.com/politics/cruz-border-security-bill',
      image_url: 'https://picsum.photos/seed/art-c1-1/400/225',
      snippet: 'The sweeping proposal includes funding for physical barriers, drone surveillance technology, and 15,000 additional Border Patrol agents.',
      published_date: '2026-03-19T08:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-C001098-2',
      person_id: 'C001098',
      title: 'Cruz Defends Second Amendment Rights at NRA Annual Conference',
      source: 'AP News',
      url: 'https://apnews.com/article/cruz-nra-speech',
      image_url: 'https://picsum.photos/seed/art-c1-2/400/225',
      snippet: 'The Texas senator drew a standing ovation with his address criticizing proposed federal firearm regulations as unconstitutional overreach.',
      published_date: '2026-03-12T16:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-C001098-3',
      person_id: 'C001098',
      title: "Cruz's Tax Cut Proposal Would Add $1.8T to Deficit, CBO Finds",
      source: 'Washington Post',
      url: 'https://washingtonpost.com/cruz-tax-cut-cbo',
      image_url: 'https://picsum.photos/seed/art-c1-3/400/225',
      snippet: 'The Congressional Budget Office projects that the proposed corporate and individual rate cuts would significantly increase federal borrowing over the next decade.',
      published_date: '2026-03-05T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-C001098-4',
      person_id: 'C001098',
      title: 'Opinion: Cruz Is Right About ACA — It Needs Fundamental Reform',
      source: 'Wall Street Journal',
      url: 'https://wsj.com/opinion/cruz-aca-reform',
      image_url: null,
      snippet: 'The senator\'s market-based healthcare proposal offers a pragmatic alternative to the current system\'s rising premiums and narrowing provider networks.',
      published_date: '2026-02-26T07:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-C001098-5',
      person_id: 'C001098',
      title: 'Cruz Podcast Reaches 5 Million Monthly Listeners',
      source: 'The Hill',
      url: 'https://thehill.com/cruz-podcast-milestone',
      image_url: 'https://picsum.photos/seed/art-c1-5/400/225',
      snippet: '"Verdict with Ted Cruz" has become one of the most-listened political podcasts, blending policy commentary with pop culture references.',
      published_date: '2026-02-18T10:00:00Z',
      content_type: 'blog',
    },
    {
      id: 'art-C001098-6',
      person_id: 'C001098',
      title: 'Cruz Blocks Judicial Nominee Over Immigration Ruling Record',
      source: 'Reuters',
      url: 'https://reuters.com/cruz-judicial-nominee-block',
      image_url: 'https://picsum.photos/seed/art-c1-6/400/225',
      snippet: 'The senator placed a hold on the 9th Circuit nomination, citing the nominee\'s record on asylum and border enforcement cases.',
      published_date: '2026-02-10T13:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-C001098-7',
      person_id: 'C001098',
      title: 'Senator Cruz Announces Texas Energy Independence Tour',
      source: 'Office of Sen. Cruz',
      url: 'https://cruz.senate.gov/newsroom/energy-tour',
      image_url: null,
      snippet: 'A five-city tour highlighting Texas energy production, LNG exports, and opposition to federal regulations on fossil fuels.',
      published_date: '2026-02-01T09:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-C001098-8',
      person_id: 'C001098',
      title: 'Cruz and Cornyn Introduce Bill to Expedite Oil Drilling Permits',
      source: 'Houston Chronicle',
      url: 'https://houstonchronicle.com/cruz-drilling-permits',
      image_url: 'https://picsum.photos/seed/art-c1-8/400/225',
      snippet: 'The bipartisan Texas duo aims to cut federal permit review timelines from 4 years to 6 months for new drilling operations.',
      published_date: '2026-01-25T11:00:00Z',
      content_type: 'news',
    },
  ],

  // ── Senator Kyrsten Sinema (S001191) ──
  S001191: [
    {
      id: 'art-S001191-1',
      person_id: 'S001191',
      title: 'Sinema Brokers Bipartisan Deal on Prescription Drug Imports',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/sinema-drug-import-deal',
      image_url: 'https://picsum.photos/seed/art-s3-1/400/225',
      snippet: 'The independent senator secured support from both parties for a bill allowing bulk importation of FDA-approved drugs from Canada.',
      published_date: '2026-03-17T09:30:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001191-2',
      person_id: 'S001191',
      title: 'Sinema\'s Independent Path: One Year Without a Party',
      source: 'Politico',
      url: 'https://politico.com/sinema-independent-year',
      image_url: 'https://picsum.photos/seed/art-s3-2/400/225',
      snippet: 'A look at how the Arizona senator has navigated the chamber as its only independent, casting pivotal swing votes on 14 major bills.',
      published_date: '2026-03-08T12:00:00Z',
      content_type: 'blog',
    },
    {
      id: 'art-S001191-3',
      person_id: 'S001191',
      title: 'Sinema Pushes Immigration Reform With Border Community Focus',
      source: 'AP News',
      url: 'https://apnews.com/sinema-immigration-reform',
      image_url: 'https://picsum.photos/seed/art-s3-3/400/225',
      snippet: 'The proposal prioritizes funding for border town infrastructure, asylum processing centers, and work visa streamlining.',
      published_date: '2026-02-28T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001191-4',
      person_id: 'S001191',
      title: 'Opinion: Sinema Shows What Centrism Can Actually Accomplish',
      source: 'The Atlantic',
      url: 'https://theatlantic.com/opinion/sinema-centrism',
      image_url: null,
      snippet: 'Love her or loathe her, the senator\'s recent legislative wins prove that the political center can still drive meaningful policy outcomes.',
      published_date: '2026-02-20T08:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-S001191-5',
      person_id: 'S001191',
      title: 'Sinema Votes to Confirm New FDA Commissioner in Narrow 51-49 Vote',
      source: 'CNN',
      url: 'https://cnn.com/sinema-fda-vote',
      image_url: 'https://picsum.photos/seed/art-s3-5/400/225',
      snippet: 'The Arizona senator was the deciding vote, citing the nominee\'s commitment to accelerating generic drug approvals and lowering costs.',
      published_date: '2026-02-12T16:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001191-6',
      person_id: 'S001191',
      title: 'Sen. Sinema Announces $200M in Federal Grants for Arizona Water Infrastructure',
      source: 'Office of Sen. Sinema',
      url: 'https://sinema.senate.gov/newsroom/water-grants',
      image_url: null,
      snippet: 'Federal funding will support water recycling, drought mitigation, and canal modernization projects across Maricopa and Pima counties.',
      published_date: '2026-02-05T10:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-S001191-7',
      person_id: 'S001191',
      title: 'Sinema and Manchin Launch Bipartisan Caucus for Climate Pragmatism',
      source: 'The Hill',
      url: 'https://thehill.com/sinema-manchin-climate-caucus',
      image_url: 'https://picsum.photos/seed/art-s3-7/400/225',
      snippet: 'The new caucus seeks to find middle ground between green energy mandates and fossil fuel interests, focusing on nuclear and carbon capture.',
      published_date: '2026-01-28T13:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001191-8',
      person_id: 'S001191',
      title: 'Sinema Town Hall Draws 800 in Tucson for Healthcare Discussion',
      source: 'Tucson Sentinel',
      url: 'https://tucsonsentinel.com/sinema-town-hall',
      image_url: 'https://picsum.photos/seed/art-s3-8/400/225',
      snippet: 'Residents pressed the senator on drug costs, Medicare eligibility, and rural hospital closures during a two-hour session at the Tucson Convention Center.',
      published_date: '2026-01-20T11:00:00Z',
      content_type: 'news',
    },
  ],

  // ── Senator Mark Kelly (K000377) ──
  K000377: [
    {
      id: 'art-K000377-1',
      person_id: 'K000377',
      title: 'Kelly Secures $340M for Arizona Veterans Healthcare Expansion',
      source: 'AP News',
      url: 'https://apnews.com/kelly-veterans-healthcare',
      image_url: 'https://picsum.photos/seed/art-k1-1/400/225',
      snippet: 'New VA facilities planned for Phoenix and Flagstaff will serve an estimated 120,000 veterans currently facing long wait times.',
      published_date: '2026-03-20T08:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-K000377-2',
      person_id: 'K000377',
      title: 'Kelly Champions Clean Water Act Amendments for Rural Arizona',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/kelly-clean-water',
      image_url: 'https://picsum.photos/seed/art-k1-2/400/225',
      snippet: 'The amendments would allocate $180M for water treatment upgrades in communities affected by PFAS contamination in Pinal and Yuma counties.',
      published_date: '2026-03-13T10:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-K000377-3',
      person_id: 'K000377',
      title: 'From Astronaut to Senator: Kelly\'s Unique Perspective on National Security',
      source: 'The Atlantic',
      url: 'https://theatlantic.com/kelly-astronaut-senator',
      image_url: 'https://picsum.photos/seed/art-k1-3/400/225',
      snippet: 'How four Space Shuttle missions shaped the Arizona senator\'s approach to defense spending, border technology, and scientific research funding.',
      published_date: '2026-03-04T09:00:00Z',
      content_type: 'blog',
    },
    {
      id: 'art-K000377-4',
      person_id: 'K000377',
      title: 'Opinion: Kelly\'s Border Plan Balances Security With Compassion',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/opinion/kelly-border-plan',
      image_url: null,
      snippet: 'The senator\'s proposal for technology-driven border security avoids the wall debate while addressing genuine humanitarian concerns at the border.',
      published_date: '2026-02-24T07:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-K000377-5',
      person_id: 'K000377',
      title: 'Kelly Co-Sponsors Affordable Housing Bill Targeting Western States',
      source: 'Reuters',
      url: 'https://reuters.com/kelly-housing-bill',
      image_url: 'https://picsum.photos/seed/art-k1-5/400/225',
      snippet: 'The bill would incentivize construction of 500,000 affordable units across Arizona, Nevada, and Colorado by offering tax credits to developers.',
      published_date: '2026-02-15T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-K000377-6',
      person_id: 'K000377',
      title: 'Senator Kelly Announces Prescription Drug Savings Program for Seniors',
      source: 'Office of Sen. Kelly',
      url: 'https://kelly.senate.gov/newsroom/drug-savings',
      image_url: null,
      snippet: 'The program connects Arizona seniors with existing federal discounts, estimated to save participants an average of $1,200 annually on medications.',
      published_date: '2026-02-08T10:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-K000377-7',
      person_id: 'K000377',
      title: 'Kelly Visits Border With Bipartisan Senate Delegation',
      source: 'CNN',
      url: 'https://cnn.com/kelly-border-visit',
      image_url: 'https://picsum.photos/seed/art-k1-7/400/225',
      snippet: 'A six-senator group toured Nogales and Douglas processing facilities, with Kelly emphasizing the need for more asylum judges and infrastructure.',
      published_date: '2026-01-30T16:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-K000377-8',
      person_id: 'K000377',
      title: 'Kelly Pushes NASA Funding Increase in Appropriations Committee',
      source: 'Space News',
      url: 'https://spacenews.com/kelly-nasa-funding',
      image_url: 'https://picsum.photos/seed/art-k1-8/400/225',
      snippet: 'The former astronaut advocates for a 12% budget increase for NASA, focusing on Artemis program milestones and climate observation satellites.',
      published_date: '2026-01-22T11:00:00Z',
      content_type: 'news',
    },
  ],

  // ── Rep Ruben Gallego (G000574) ──
  G000574: [
    {
      id: 'art-G000574-1',
      person_id: 'G000574',
      title: 'Gallego Introduces Veterans Mental Health Access Act',
      source: 'AP News',
      url: 'https://apnews.com/gallego-veterans-mental-health',
      image_url: 'https://picsum.photos/seed/art-g1-1/400/225',
      snippet: 'The bill would expand same-day mental health appointments at VA facilities and fund 2,000 new counselor positions nationwide.',
      published_date: '2026-03-16T10:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-G000574-2',
      person_id: 'G000574',
      title: 'Gallego Fights for $35 Insulin Cap Extension to Uninsured Americans',
      source: 'Phoenix New Times',
      url: 'https://phoenixnewtimes.com/gallego-insulin-cap',
      image_url: 'https://picsum.photos/seed/art-g1-2/400/225',
      snippet: 'The AZ-3 representative argues that the current cap only covers insured patients, leaving 2.5 million uninsured diabetics without price relief.',
      published_date: '2026-03-09T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-G000574-3',
      person_id: 'G000574',
      title: 'Opinion: Gallego Is the Future of the Arizona Democratic Party',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/opinion/gallego-az-future',
      image_url: null,
      snippet: 'With his Marine veteran background and working-class roots, the young congressman represents a new model for Democratic candidates in purple states.',
      published_date: '2026-02-28T08:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-G000574-4',
      person_id: 'G000574',
      title: 'Gallego Secures Clean Energy Jobs Grant for Phoenix Metro',
      source: 'Reuters',
      url: 'https://reuters.com/gallego-clean-energy-phoenix',
      image_url: 'https://picsum.photos/seed/art-g1-4/400/225',
      snippet: 'A $45M federal grant will fund solar panel manufacturing training and installation jobs, creating an estimated 3,000 positions in Maricopa County.',
      published_date: '2026-02-18T12:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-G000574-5',
      person_id: 'G000574',
      title: 'Gallego Hosts Housing Affordability Summit in Downtown Phoenix',
      source: 'AZ Central',
      url: 'https://azcentral.com/gallego-housing-summit',
      image_url: 'https://picsum.photos/seed/art-g1-5/400/225',
      snippet: 'Local developers, nonprofits, and city officials gathered to discuss zoning reforms and federal programs to address the housing crisis in District 3.',
      published_date: '2026-02-10T11:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-G000574-6',
      person_id: 'G000574',
      title: 'Rep. Gallego Announces Town Hall Schedule for Spring Recess',
      source: 'Office of Rep. Gallego',
      url: 'https://gallego.house.gov/newsroom/town-halls',
      image_url: null,
      snippet: 'Four community meetings across AZ-3 will cover veterans services, prescription drug costs, and neighborhood safety initiatives.',
      published_date: '2026-02-03T09:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-G000574-7',
      person_id: 'G000574',
      title: 'A Marine\'s Mission on Capitol Hill',
      source: 'Military Times',
      url: 'https://militarytimes.com/gallego-marine-congress',
      image_url: 'https://picsum.photos/seed/art-g1-7/400/225',
      snippet: 'How Gallego\'s combat experience in Iraq informs his push for better VA services and his bipartisan work on the Armed Services Committee.',
      published_date: '2026-01-26T10:00:00Z',
      content_type: 'blog',
    },
    {
      id: 'art-G000574-8',
      person_id: 'G000574',
      title: 'Gallego Joins Push for Federal Wildfire Prevention Funding',
      source: 'High Country News',
      url: 'https://hcn.org/gallego-wildfire-funding',
      image_url: 'https://picsum.photos/seed/art-g1-8/400/225',
      snippet: 'Arizona representatives rally for $2B in wildfire prevention after record-setting fire seasons threaten communities near Prescott National Forest.',
      published_date: '2026-01-18T13:00:00Z',
      content_type: 'news',
    },
  ],

  // ── Rep David Schweikert (S001183) ──
  S001183: [
    {
      id: 'art-S001183-1',
      person_id: 'S001183',
      title: 'Schweikert Proposes AI-Powered Government Efficiency Dashboard',
      source: 'The Hill',
      url: 'https://thehill.com/schweikert-ai-government',
      image_url: 'https://picsum.photos/seed/art-ds-1/400/225',
      snippet: 'The AZ-1 congressman wants to use machine learning to identify duplicative federal programs, projecting $80B in potential savings.',
      published_date: '2026-03-15T09:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001183-2',
      person_id: 'S001183',
      title: 'Schweikert Leads House Floor Charts on National Debt Crisis',
      source: 'C-SPAN',
      url: 'https://cspan.org/schweikert-debt-charts',
      image_url: 'https://picsum.photos/seed/art-ds-2/400/225',
      snippet: 'Known for his data-driven floor speeches, the congressman presented 47 charts showing the trajectory of mandatory spending over the next 30 years.',
      published_date: '2026-03-07T15:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001183-3',
      person_id: 'S001183',
      title: 'Schweikert Pushes Tax Reform to Boost Small Business Innovation',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/schweikert-tax-reform',
      image_url: 'https://picsum.photos/seed/art-ds-3/400/225',
      snippet: 'The proposal would expand R&D tax credits for businesses under 500 employees and eliminate capital gains on investments in domestic startups.',
      published_date: '2026-02-25T10:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001183-4',
      person_id: 'S001183',
      title: 'Opinion: Schweikert\'s Tech-First Approach to Government Is Overdue',
      source: 'Wall Street Journal',
      url: 'https://wsj.com/opinion/schweikert-tech-government',
      image_url: null,
      snippet: 'The congressman\'s vision for automating government services could save taxpayers billions while improving citizen experience with federal agencies.',
      published_date: '2026-02-16T07:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-S001183-5',
      person_id: 'S001183',
      title: 'Schweikert Advocates for Cryptocurrency Regulatory Framework',
      source: 'CoinDesk',
      url: 'https://coindesk.com/schweikert-crypto-framework',
      image_url: 'https://picsum.photos/seed/art-ds-5/400/225',
      snippet: 'A new bill would classify digital assets under existing SEC and CFTC jurisdictions while providing safe harbors for emerging DeFi protocols.',
      published_date: '2026-02-08T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001183-6',
      person_id: 'S001183',
      title: 'Rep. Schweikert Announces AZ-1 Technology Innovation Grants',
      source: 'Office of Rep. Schweikert',
      url: 'https://schweikert.house.gov/newsroom/tech-grants',
      image_url: null,
      snippet: 'Small tech businesses in Scottsdale and North Phoenix can apply for up to $250K in federal innovation grants through the SBA partnership.',
      published_date: '2026-01-30T10:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-S001183-7',
      person_id: 'S001183',
      title: 'Schweikert Joins Border Security Caucus Field Trip to Yuma',
      source: 'Fox 10 Phoenix',
      url: 'https://fox10phoenix.com/schweikert-yuma-border',
      image_url: 'https://picsum.photos/seed/art-ds-7/400/225',
      snippet: 'House Republicans toured the Yuma Sector to assess technology deployments including ground sensors, cameras, and autonomous surveillance drones.',
      published_date: '2026-01-22T16:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001183-8',
      person_id: 'S001183',
      title: 'The Data Nerd of Congress: Inside Schweikert\'s Policy Lab',
      source: 'Wired',
      url: 'https://wired.com/schweikert-policy-data',
      image_url: 'https://picsum.photos/seed/art-ds-8/400/225',
      snippet: 'How the congressman uses demographic modeling, CBO projections, and custom spreadsheets to build his signature data-driven floor presentations.',
      published_date: '2026-01-14T09:00:00Z',
      content_type: 'blog',
    },
  ],

  // ── Rep Andy Biggs (B001302) ──
  B001302: [
    {
      id: 'art-B001302-1',
      person_id: 'B001302',
      title: 'Biggs Leads House Freedom Caucus Push for Spending Cuts',
      source: 'Washington Examiner',
      url: 'https://washingtonexaminer.com/biggs-spending-cuts',
      image_url: 'https://picsum.photos/seed/art-ab-1/400/225',
      snippet: 'The AZ-5 congressman demands $200B in discretionary spending reductions as a condition for supporting the upcoming continuing resolution.',
      published_date: '2026-03-18T11:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-B001302-2',
      person_id: 'B001302',
      title: 'Biggs Challenges EPA Authority on Arizona Water Regulations',
      source: 'AP News',
      url: 'https://apnews.com/biggs-epa-water',
      image_url: 'https://picsum.photos/seed/art-ab-2/400/225',
      snippet: 'The congressman argues that federal water regulations are overstepping state jurisdiction and harming Arizona agricultural communities.',
      published_date: '2026-03-10T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-B001302-3',
      person_id: 'B001302',
      title: 'Biggs Introduces Constitutional Carry Reciprocity Act',
      source: 'The Federalist',
      url: 'https://thefederalist.com/biggs-carry-reciprocity',
      image_url: 'https://picsum.photos/seed/art-ab-3/400/225',
      snippet: 'The bill would require all 50 states to recognize concealed carry permits from any other state, citing Second Amendment protections.',
      published_date: '2026-03-01T08:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-B001302-4',
      person_id: 'B001302',
      title: 'Opinion: Biggs Stands Firm Against Runaway Federal Spending',
      source: 'National Review',
      url: 'https://nationalreview.com/opinion/biggs-federal-spending',
      image_url: null,
      snippet: 'In a caucus increasingly willing to compromise, the Arizona conservative remains a principled voice for fiscal discipline and limited government.',
      published_date: '2026-02-22T07:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-B001302-5',
      person_id: 'B001302',
      title: 'Biggs Questions Climate Science Funding at House Committee Hearing',
      source: 'CNN',
      url: 'https://cnn.com/biggs-climate-hearing',
      image_url: 'https://picsum.photos/seed/art-ab-5/400/225',
      snippet: 'The congressman pressed NOAA officials on research methodology and called for an independent audit of climate modeling expenditures.',
      published_date: '2026-02-14T15:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-B001302-6',
      person_id: 'B001302',
      title: 'Rep. Biggs Announces Opposition to Omnibus Spending Bill',
      source: 'Office of Rep. Biggs',
      url: 'https://biggs.house.gov/newsroom/omnibus-opposition',
      image_url: null,
      snippet: 'Citing $1.7T in total spending, the congressman calls the omnibus "a dereliction of fiscal duty" and urges individual appropriations votes.',
      published_date: '2026-02-06T10:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-B001302-7',
      person_id: 'B001302',
      title: 'Biggs Tours Border Wall Construction Sites in AZ-5',
      source: 'Fox News',
      url: 'https://foxnews.com/biggs-border-wall-tour',
      image_url: 'https://picsum.photos/seed/art-ab-7/400/225',
      snippet: 'The congressman documented gaps in border infrastructure and called for immediate resumption of wall construction in the Tucson Sector.',
      published_date: '2026-01-28T12:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-B001302-8',
      person_id: 'B001302',
      title: 'Inside the Freedom Caucus: How Biggs Wields Influence',
      source: 'Axios',
      url: 'https://axios.com/biggs-freedom-caucus-influence',
      image_url: 'https://picsum.photos/seed/art-ab-8/400/225',
      snippet: 'As a senior Freedom Caucus member, Biggs has repeatedly used procedural leverage to shape spending bills and leadership negotiations.',
      published_date: '2026-01-19T10:00:00Z',
      content_type: 'blog',
    },
  ],

  // ── Rep Greg Stanton (S001211) ──
  S001211: [
    {
      id: 'art-S001211-1',
      person_id: 'S001211',
      title: 'Stanton Secures $28M for Phoenix Light Rail Extension',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/stanton-light-rail',
      image_url: 'https://picsum.photos/seed/art-gs-1/400/225',
      snippet: 'Federal transit funding will extend the Valley Metro line into South Phoenix, connecting underserved communities to downtown job centers.',
      published_date: '2026-03-19T09:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001211-2',
      person_id: 'S001211',
      title: 'Stanton Champions Affordable Childcare Tax Credit Expansion',
      source: 'Reuters',
      url: 'https://reuters.com/stanton-childcare-credit',
      image_url: 'https://picsum.photos/seed/art-gs-2/400/225',
      snippet: 'The bill would double the child and dependent care tax credit to $6,000 per child for families earning under $150,000 annually.',
      published_date: '2026-03-11T12:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001211-3',
      person_id: 'S001211',
      title: 'Stanton Pushes Clean Energy Manufacturing for AZ-4',
      source: 'Phoenix Business Journal',
      url: 'https://bizjournals.com/phoenix/stanton-clean-energy',
      image_url: 'https://picsum.photos/seed/art-gs-3/400/225',
      snippet: 'The congressman is working to attract battery and EV component manufacturers to the East Valley, projecting 5,000 new jobs by 2028.',
      published_date: '2026-03-03T10:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001211-4',
      person_id: 'S001211',
      title: 'Opinion: Stanton\'s Pragmatic Approach to Healthcare Is Working',
      source: 'Arizona Republic',
      url: 'https://azcentral.com/opinion/stanton-healthcare',
      image_url: null,
      snippet: 'Rather than sweeping overhauls, the former Phoenix mayor focuses on targeted fixes — drug pricing, telehealth expansion, and community health centers.',
      published_date: '2026-02-22T08:00:00Z',
      content_type: 'opinion',
    },
    {
      id: 'art-S001211-5',
      person_id: 'S001211',
      title: 'Stanton Fights to Keep Title I Funding for Arizona Schools',
      source: 'Education Week',
      url: 'https://edweek.org/stanton-title-i-funding',
      image_url: 'https://picsum.photos/seed/art-gs-5/400/225',
      snippet: 'With proposed federal education cuts, the congressman rallies to protect $380M in annual Title I allocations for Arizona\'s highest-poverty school districts.',
      published_date: '2026-02-12T14:00:00Z',
      content_type: 'news',
    },
    {
      id: 'art-S001211-6',
      person_id: 'S001211',
      title: 'Rep. Stanton Announces Healthcare Enrollment Assistance Events',
      source: 'Office of Rep. Stanton',
      url: 'https://stanton.house.gov/newsroom/healthcare-enrollment',
      image_url: null,
      snippet: 'Free enrollment assistance sessions will help AZ-4 residents sign up for ACA marketplace plans and Medicaid during the open enrollment extension.',
      published_date: '2026-02-04T10:00:00Z',
      content_type: 'press_release',
    },
    {
      id: 'art-S001211-7',
      person_id: 'S001211',
      title: 'From Mayor to Congressman: Stanton\'s Local-First Governance',
      source: 'Governing Magazine',
      url: 'https://governing.com/stanton-local-governance',
      image_url: 'https://picsum.photos/seed/art-gs-7/400/225',
      snippet: 'How eight years as Phoenix\'s mayor shaped the congressman\'s emphasis on infrastructure, transit, and community-level policymaking in Congress.',
      published_date: '2026-01-27T09:00:00Z',
      content_type: 'blog',
    },
    {
      id: 'art-S001211-8',
      person_id: 'S001211',
      title: 'Stanton Co-Sponsors Bipartisan Bill to Lower Prescription Drug Costs',
      source: 'The Hill',
      url: 'https://thehill.com/stanton-drug-costs-bill',
      image_url: 'https://picsum.photos/seed/art-gs-8/400/225',
      snippet: 'The legislation would allow Medicare to negotiate prices on 50 additional drugs beyond the current IRA provisions, projected to save $30B over a decade.',
      published_date: '2026-01-20T13:00:00Z',
      content_type: 'news',
    },
  ],
}

// ── Fallback article generator for persons without specific mock data ──

function generateFallbackArticles(personId: string, personName: string): PersonArticle[] {
  const firstName = personName.split(' ')[0]
  const lastName = personName.split(' ').slice(-1)[0]

  return [
    {
      id: `art-${personId}-1`,
      person_id: personId,
      title: `${personName} Gains Momentum in Latest Polling Data`,
      source: 'Politico',
      url: 'https://politico.com/article/polling-update',
      image_url: `https://picsum.photos/seed/art-${personId}-1/400/225`,
      snippet: `New survey data shows ${lastName} with growing support among independent voters and suburban demographics in key swing districts.`,
      published_date: '2026-03-17T10:00:00Z',
      content_type: 'news',
    },
    {
      id: `art-${personId}-2`,
      person_id: personId,
      title: `${personName} Outlines Vision for Economic Growth`,
      source: 'Reuters',
      url: 'https://reuters.com/article/economic-vision',
      image_url: `https://picsum.photos/seed/art-${personId}-2/400/225`,
      snippet: `In a wide-ranging policy speech, ${lastName} detailed plans for job creation, small business tax relief, and workforce development programs.`,
      published_date: '2026-03-10T14:00:00Z',
      content_type: 'news',
    },
    {
      id: `art-${personId}-3`,
      person_id: personId,
      title: `Opinion: What ${firstName} ${lastName}'s Record Tells Us`,
      source: 'The Atlantic',
      url: 'https://theatlantic.com/opinion/record-analysis',
      image_url: null,
      snippet: `A careful examination of voting patterns and public statements reveals a more nuanced political identity than campaign rhetoric suggests.`,
      published_date: '2026-03-03T08:00:00Z',
      content_type: 'opinion',
    },
    {
      id: `art-${personId}-4`,
      person_id: personId,
      title: `${personName} Addresses Healthcare Costs at Town Hall`,
      source: 'AP News',
      url: 'https://apnews.com/article/healthcare-town-hall',
      image_url: `https://picsum.photos/seed/art-${personId}-4/400/225`,
      snippet: `Constituents pressed ${lastName} on prescription drug pricing, insurance premiums, and the future of Medicare during a packed community event.`,
      published_date: '2026-02-24T12:00:00Z',
      content_type: 'news',
    },
    {
      id: `art-${personId}-5`,
      person_id: personId,
      title: `${personName} Takes Stand on Education Funding`,
      source: 'Education Week',
      url: 'https://edweek.org/education-funding-stance',
      image_url: `https://picsum.photos/seed/art-${personId}-5/400/225`,
      snippet: `${lastName} called for increased K-12 investment and teacher pay raises while debating the role of federal oversight in local school districts.`,
      published_date: '2026-02-16T10:00:00Z',
      content_type: 'news',
    },
    {
      id: `art-${personId}-6`,
      person_id: personId,
      title: `${personName}'s Campaign Strategy: A Closer Look`,
      source: 'Axios',
      url: 'https://axios.com/campaign-strategy-analysis',
      image_url: `https://picsum.photos/seed/art-${personId}-6/400/225`,
      snippet: `Digital outreach, grassroots organizing, and targeted messaging in key precincts form the backbone of ${lastName}'s approach to winning votes.`,
      published_date: '2026-02-08T09:00:00Z',
      content_type: 'blog',
    },
    {
      id: `art-${personId}-7`,
      person_id: personId,
      title: `${personName} Releases Statement on Infrastructure Investment`,
      source: `Office of ${personName}`,
      url: 'https://example.com/newsroom/infrastructure',
      image_url: null,
      snippet: `Federal infrastructure dollars should prioritize roads, bridges, and broadband in underserved communities, ${lastName} stated in a detailed policy brief.`,
      published_date: '2026-01-30T11:00:00Z',
      content_type: 'press_release',
    },
    {
      id: `art-${personId}-8`,
      person_id: personId,
      title: `${personName} Pledges Action on Climate and Energy Policy`,
      source: 'CNN',
      url: 'https://cnn.com/climate-energy-pledge',
      image_url: `https://picsum.photos/seed/art-${personId}-8/400/225`,
      snippet: `Balancing economic growth with environmental responsibility, ${lastName} proposed a mix of clean energy incentives and emission reduction targets.`,
      published_date: '2026-01-22T15:00:00Z',
      content_type: 'news',
    },
  ]
}

// ── Public API ──────────────────────────────────────────────────────

const SIMULATED_DELAY = 300

export async function getPersonArticles(
  personId: string,
  personName: string
): Promise<PersonArticle[]> {
  await new Promise((r) => setTimeout(r, SIMULATED_DELAY))

  // Return specific mock data if available, otherwise generate fallback
  return MOCK_ARTICLES[personId] ?? generateFallbackArticles(personId, personName)
}
