// Notification API — profile-driven notification generation
// Notifications are generated by matching bills/actions against the user's profile.
// Each notification is unique per content item — no duplicates, no spam.

import type { User } from '@/api/auth'
import type { Bill } from '@/api/bills'
import type { GovernmentAction } from '@/api/actions'
import {
  buildUserRelevance,
  scoreRelevance,
  buildRelevanceReason,
  type UserRelevance,
} from '@/lib/personalization'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface Notification {
  id: string
  type: 'bill_alert' | 'status_change' | 'action_alert' | 'rep_voted'
  // Link target — one of these will be set
  bill_id?: string
  action_id?: string
  title: string
  message: string
  reason: string // Why this is relevant to the user
  impact_level: 'high' | 'medium' | 'low'
  read: boolean
  created_at: string
}

// ---------------------------------------------------------------------------
// Internal state — tracks what the user has already been notified about
// ---------------------------------------------------------------------------

const seenContentIds = new Set<string>()
const readIds = new Set<string>()
let generatedNotifications: Notification[] = []

let preferences: Record<string, boolean> = {
  bill_alerts: true,
  status_changes: true,
  action_alerts: true,
  rep_votes: true,
  high_impact_only: false,
  email_digest: false,
  push_notifications: true,
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function delay(ms: number = 300): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

/** Generate a stable notification ID from content type + content ID */
function makeNotifId(type: string, contentId: string): string {
  return `notif-${type}-${contentId}`
}

// ---------------------------------------------------------------------------
// Notification generation from bills
// ---------------------------------------------------------------------------

function generateBillNotification(
  bill: Bill,
  relevance: UserRelevance,
  userState?: string
): Notification | null {
  const score = scoreRelevance(
    relevance,
    {
      categories: bill.categories,
      title: bill.title,
      summary: bill.summary_ai,
      affected_personas: Object.keys(bill.impact_personas),
      state_relevance: bill.state_relevance,
    },
    userState
  )

  // Only notify if score >= 20 (some meaningful relevance)
  if (score < 20) return null

  const id = makeNotifId('bill', bill.id)
  if (seenContentIds.has(id)) return null

  const impact: 'high' | 'medium' | 'low' =
    score >= 60 ? 'high' : score >= 35 ? 'medium' : 'low'

  // Skip low-impact if user only wants high impact
  if (preferences.high_impact_only && impact === 'low') return null

  const reason = buildRelevanceReason(relevance, {
    categories: bill.categories,
    title: bill.title,
    summary: bill.summary_ai,
    affected_personas: Object.keys(bill.impact_personas),
  })

  // Determine notification type based on bill status
  let type: Notification['type'] = 'bill_alert'
  let title = ''
  let message = ''

  if (bill.status === 'enacted') {
    type = 'status_change'
    title = `${bill.short_title} signed into law`
    message = `${bill.status_detail} ${bill.summary_ai.split('.').slice(0, 1).join('.')}.`
  } else if (bill.status === 'passed_house' || bill.status === 'passed_senate') {
    type = 'status_change'
    const chamber = bill.status === 'passed_house' ? 'the House' : 'the Senate'
    title = `${bill.short_title} passed ${chamber}`
    message = `${bill.status_detail}`
  } else if (bill.status === 'vetoed') {
    type = 'status_change'
    title = `${bill.short_title} vetoed`
    message = bill.status_detail
  } else {
    title = `New bill may affect you: ${bill.short_title}`
    message = bill.summary_ai.split('.').slice(0, 2).join('.') + '.'
  }

  if (!preferences.bill_alerts && type === 'bill_alert') return null
  if (!preferences.status_changes && type === 'status_change') return null

  return {
    id,
    type,
    bill_id: bill.id,
    title,
    message,
    reason,
    impact_level: impact,
    read: readIds.has(id),
    created_at: bill.last_action_date + 'T12:00:00Z',
  }
}

// ---------------------------------------------------------------------------
// Notification generation from actions
// ---------------------------------------------------------------------------

function generateActionNotification(
  action: GovernmentAction,
  relevance: UserRelevance,
  userState?: string
): Notification | null {
  const score = scoreRelevance(
    relevance,
    {
      categories: action.categories,
      title: action.title,
      summary: action.summary_ai,
      affected_personas: action.affected_personas,
      impact_level: action.impact_level,
      state_relevance: action.state_relevance,
    },
    userState
  )

  if (score < 20) return null

  const id = makeNotifId('action', action.id)
  if (seenContentIds.has(id)) return null

  const impact: 'high' | 'medium' | 'low' =
    score >= 60 ? 'high' : score >= 35 ? 'medium' : 'low'

  if (preferences.high_impact_only && impact === 'low') return null
  if (!preferences.action_alerts) return null

  const reason = buildRelevanceReason(relevance, {
    categories: action.categories,
    title: action.title,
    summary: action.summary_ai,
    affected_personas: action.affected_personas,
  })

  const TYPE_LABELS: Record<string, string> = {
    executive_order: 'Executive Order',
    proclamation: 'Proclamation',
    memorandum: 'Presidential Memorandum',
    final_rule: 'Final Rule',
    proposed_rule: 'Proposed Rule',
    court_ruling: 'Court Ruling',
    agency_action: 'Agency Action',
  }
  const typeLabel = TYPE_LABELS[action.action_type] ?? action.action_type

  return {
    id,
    type: 'action_alert',
    action_id: action.id,
    title: `${typeLabel}: ${action.title.length > 60 ? action.title.slice(0, 57) + '...' : action.title}`,
    message: action.summary_ai.split('.').slice(0, 2).join('.') + '.',
    reason,
    impact_level: impact,
    read: readIds.has(id),
    created_at: (action.effective_date || action.signing_date || action.publication_date) + 'T12:00:00Z',
  }
}

// ---------------------------------------------------------------------------
// Main generation — called by the store
// ---------------------------------------------------------------------------

export async function generateNotifications(
  user: User,
  profiles: string[],
  categories: string[],
  bills: Bill[],
  actions: GovernmentAction[]
): Promise<void> {
  const relevance = buildUserRelevance(user, profiles, categories)

  const newNotifs: Notification[] = []

  for (const bill of bills) {
    const notif = generateBillNotification(bill, relevance, user.state_code)
    if (notif) {
      seenContentIds.add(notif.id)
      newNotifs.push(notif)
    }
  }

  for (const action of actions) {
    const notif = generateActionNotification(action, relevance, user.state_code)
    if (notif) {
      seenContentIds.add(notif.id)
      newNotifs.push(notif)
    }
  }

  // Merge with existing, keeping uniqueness by id
  const existingById = new Map(generatedNotifications.map((n) => [n.id, n]))
  for (const n of newNotifs) {
    if (!existingById.has(n.id)) {
      existingById.set(n.id, n)
    }
  }

  // Sort: unread first, then by impact (high > medium > low), then by date
  generatedNotifications = [...existingById.values()].sort((a, b) => {
    // Unread first
    if (a.read !== b.read) return a.read ? 1 : -1
    // Impact weight
    const impactW: Record<string, number> = { high: 3, medium: 2, low: 1 }
    const wDiff = (impactW[b.impact_level] ?? 1) - (impactW[a.impact_level] ?? 1)
    if (wDiff !== 0) return wDiff
    // Recency
    return new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  })
}

// ---------------------------------------------------------------------------
// Public API (consumed by the store)
// ---------------------------------------------------------------------------

export async function getNotifications(
  page: number = 1,
  unreadOnly: boolean = false
): Promise<Notification[]> {
  await delay(100)

  let filtered = [...generatedNotifications]
  if (unreadOnly) {
    filtered = filtered.filter((n) => !n.read)
  }

  const pageSize = 10
  const start = (page - 1) * pageSize
  return filtered.slice(start, start + pageSize)
}

export async function getUnreadCount(): Promise<number> {
  await delay(50)
  return generatedNotifications.filter((n) => !n.read).length
}

export async function markRead(id: string): Promise<void> {
  await delay(100)
  readIds.add(id)
  const notif = generatedNotifications.find((n) => n.id === id)
  if (notif) notif.read = true
}

export async function markAllRead(): Promise<void> {
  await delay(100)
  generatedNotifications.forEach((n) => {
    n.read = true
    readIds.add(n.id)
  })
}

export async function getPreferences(): Promise<Record<string, boolean>> {
  await delay(100)
  return { ...preferences }
}

export async function updatePreferences(prefs: Record<string, boolean>): Promise<void> {
  await delay(100)
  preferences = { ...preferences, ...prefs }
}

/** Get the total count of generated notifications */
export function getNotificationCount(): number {
  return generatedNotifications.length
}
